### ISSUE TITLE
All devices "No Response"

### ISSUE THREAD

**Issue by moshed** [scholtzan/homebridge-rusty-spotify#10]
All my devices show up nicely in Homebridge and the home app, however they all say "No Response" in the Home app. when I try to turn on a device in Homebridge itself it turns on but doesn't do anything to my music.

The log from Homebridge is kind of a mess but  I've attached it below.

`0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Hue","UUID":"00000013-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Saturation","UUID":"0000002F-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Color Temperature","UUID":"000000CE-0000-1000-8000-0026BB765291","iid":null,"value":140,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":140,"maxValue":500,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Characteristic Value Transition Control","UUID":"0000021E-0000-1000-8000-00000143","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Supported Characteristic Value Transition Configuration","UUID":"0000021E-0000-1000-8000-00000144","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]}],"shouldPurgeUnusedIDs":true,"controllers":{},"_setupID":null,"controllerStorage":{"initialized":false,"fileCreated":false,"purgeUnidentifiedAccessoryData":true,"trackedControllers":[],"controllerData":{},"accessoryUUID":"6c3a72ea-f623-45df-a967-f2bba4dfc3e4"}},"displayName":"Office","UUID":"6c3a72ea-f623-45df-a967-f2bba4dfc3e4","category":1})) }
Register Spotify device: Accessory { obj: JsValue(Object({"_events":{},"_eventsCount":0,"services":[{"_events":{},"_eventsCount":2,"displayName":"","UUID":"0000003E-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":2,"displayName":"Identify","UUID":"00000014-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pw"]}},{"_events":{},"_eventsCount":1,"displayName":"Manufacturer","UUID":"00000020-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Manufacturer","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Model","UUID":"00000021-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Model","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Main Floor","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Serial Number","UUID":"00000030-0000-1000-8000-0026BB765291","iid":null,"value":"Default-SerialNumber","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"0.0.0","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Accessory Flags","UUID":"000000A6-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"App Matching Identifier","UUID":"000000A4-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Configured Name","UUID":"000000E3-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Hardware Revision","UUID":"00000053-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Software Revision","UUID":"00000054-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Product Data","UUID":"00000220-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"data","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]},{"_events":{},"_eventsCount":2,"displayName":"Main Floor","UUID":"00000043-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Main Floor","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":3,"displayName":"On","UUID":"00000025-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":3,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Hue","UUID":"00000013-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Saturation","UUID":"0000002F-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Color Temperature","UUID":"000000CE-0000-1000-8000-0026BB765291","iid":null,"value":140,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":140,"maxValue":500,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Characteristic Value Transition Control","UUID":"0000021E-0000-1000-8000-00000143","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Supported Characteristic Value Transition Configuration","UUID":"0000021E-0000-1000-8000-00000144","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]}],"reachable":false,"context":{},"_associatedHAPAccessory":{"_events":{},"_eventsCount":1,"displayName":"Main Floor","UUID":"e8b51ae8-a0ad-42b1-812d-d61a8f3bde80","aid":null,"_isBridge":false,"bridged":false,"bridgedAccessories":[],"reachable":true,"category":1,"services":[{"_events":{},"_eventsCount":2,"displayName":"","UUID":"0000003E-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":2,"displayName":"Identify","UUID":"00000014-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pw"]}},{"_events":{},"_eventsCount":1,"displayName":"Manufacturer","UUID":"00000020-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Manufacturer","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Model","UUID":"00000021-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Model","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Main Floor","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Serial Number","UUID":"00000030-0000-1000-8000-0026BB765291","iid":null,"value":"Default-SerialNumber","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"0.0.0","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Accessory Flags","UUID":"000000A6-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"App Matching Identifier","UUID":"000000A4-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Configured Name","UUID":"000000E3-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Hardware Revision","UUID":"00000053-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Software Revision","UUID":"00000054-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Product Data","UUID":"00000220-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"data","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]},{"_events":{},"_eventsCount":2,"displayName":"Main Floor","UUID":"00000043-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Main Floor","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":3,"displayName":"On","UUID":"00000025-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":3,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Hue","UUID":"00000013-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Saturation","UUID":"0000002F-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Color Temperature","UUID":"000000CE-0000-1000-8000-0026BB765291","iid":null,"value":140,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":140,"maxValue":500,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Characteristic Value Transition Control","UUID":"0000021E-0000-1000-8000-00000143","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Supported Characteristic Value Transition Configuration","UUID":"0000021E-0000-1000-8000-00000144","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]}],"shouldPurgeUnusedIDs":true,"controllers":{},"_setupID":null,"controllerStorage":{"initialized":false,"fileCreated":false,"purgeUnidentifiedAccessoryData":true,"trackedControllers":[],"controllerData":{},"accessoryUUID":"e8b51ae8-a0ad-42b1-812d-d61a8f3bde80"}},"displayName":"Main Floor","UUID":"e8b51ae8-a0ad-42b1-812d-d61a8f3bde80","category":1})) }
Register Spotify device: Accessory { obj: JsValue(Object({"_events":{},"_eventsCount":0,"services":[{"_events":{},"_eventsCount":2,"displayName":"","UUID":"0000003E-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":2,"displayName":"Identify","UUID":"00000014-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pw"]}},{"_events":{},"_eventsCount":1,"displayName":"Manufacturer","UUID":"00000020-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Manufacturer","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Model","UUID":"00000021-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Model","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Kitchen","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Serial Number","UUID":"00000030-0000-1000-8000-0026BB765291","iid":null,"value":"Default-SerialNumber","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"0.0.0","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Accessory Flags","UUID":"000000A6-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"App Matching Identifier","UUID":"000000A4-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Configured Name","UUID":"000000E3-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Hardware Revision","UUID":"00000053-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Software Revision","UUID":"00000054-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Product Data","UUID":"00000220-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"data","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]},{"_events":{},"_eventsCount":2,"displayName":"Kitchen","UUID":"00000043-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Kitchen","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":3,"displayName":"On","UUID":"00000025-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":3,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Hue","UUID":"00000013-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Saturation","UUID":"0000002F-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Color Temperature","UUID":"000000CE-0000-1000-8000-0026BB765291","iid":null,"value":140,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":140,"maxValue":500,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Characteristic Value Transition Control","UUID":"0000021E-0000-1000-8000-00000143","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Supported Characteristic Value Transition Configuration","UUID":"0000021E-0000-1000-8000-00000144","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]}],"reachable":false,"context":{},"_associatedHAPAccessory":{"_events":{},"_eventsCount":1,"displayName":"Kitchen","UUID":"018618c0-e1e7-41a7-995c-1470d7258dd8","aid":null,"_isBridge":false,"bridged":false,"bridgedAccessories":[],"reachable":true,"category":1,"services":[{"_events":{},"_eventsCount":2,"displayName":"","UUID":"0000003E-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":2,"displayName":"Identify","UUID":"00000014-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pw"]}},{"_events":{},"_eventsCount":1,"displayName":"Manufacturer","UUID":"00000020-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Manufacturer","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Model","UUID":"00000021-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Model","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Kitchen","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Serial Number","UUID":"00000030-0000-1000-8000-0026BB765291","iid":null,"value":"Default-SerialNumber","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"0.0.0","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Accessory Flags","UUID":"000000A6-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"App Matching Identifier","UUID":"000000A4-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Configured Name","UUID":"000000E3-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Hardware Revision","UUID":"00000053-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Software Revision","UUID":"00000054-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Product Data","UUID":"00000220-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"data","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]},{"_events":{},"_eventsCount":2,"displayName":"Kitchen","UUID":"00000043-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Kitchen","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":3,"displayName":"On","UUID":"00000025-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":3,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Hue","UUID":"00000013-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Saturation","UUID":"0000002F-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Color Temperature","UUID":"000000CE-0000-1000-8000-0026BB765291","iid":null,"value":140,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":140,"maxValue":500,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Characteristic Value Transition Control","UUID":"0000021E-0000-1000-8000-00000143","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Supported Characteristic Value Transition Configuration","UUID":"0000021E-0000-1000-8000-00000144","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]}],"shouldPurgeUnusedIDs":true,"controllers":{},"_setupID":null,"controllerStorage":{"initialized":false,"fileCreated":false,"purgeUnidentifiedAccessoryData":true,"trackedControllers":[],"controllerData":{},"accessoryUUID":"018618c0-e1e7-41a7-995c-1470d7258dd8"}},"displayName":"Kitchen","UUID":"018618c0-e1e7-41a7-995c-1470d7258dd8","category":1})) }
Register Spotify device: Accessory { obj: JsValue(Object({"_events":{},"_eventsCount":0,"services":[{"_events":{},"_eventsCount":2,"displayName":"","UUID":"0000003E-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":2,"displayName":"Identify","UUID":"00000014-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pw"]}},{"_events":{},"_eventsCount":1,"displayName":"Manufacturer","UUID":"00000020-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Manufacturer","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Model","UUID":"00000021-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Model","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Upstairs","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Serial Number","UUID":"00000030-0000-1000-8000-0026BB765291","iid":null,"value":"Default-SerialNumber","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"0.0.0","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Accessory Flags","UUID":"000000A6-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"App Matching Identifier","UUID":"000000A4-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Configured Name","UUID":"000000E3-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Hardware Revision","UUID":"00000053-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Software Revision","UUID":"00000054-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Product Data","UUID":"00000220-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"data","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]},{"_events":{},"_eventsCount":2,"displayName":"Upstairs","UUID":"00000043-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Upstairs","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":3,"displayName":"On","UUID":"00000025-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":3,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Hue","UUID":"00000013-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Saturation","UUID":"0000002F-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Color Temperature","UUID":"000000CE-0000-1000-8000-0026BB765291","iid":null,"value":140,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":140,"maxValue":500,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Characteristic Value Transition Control","UUID":"0000021E-0000-1000-8000-00000143","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Supported Characteristic Value Transition Configuration","UUID":"0000021E-0000-1000-8000-00000144","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]}],"reachable":false,"context":{},"_associatedHAPAccessory":{"_events":{},"_eventsCount":1,"displayName":"Upstairs","UUID":"a25ab181-230b-4e67-8e7d-c65d93906846","aid":null,"_isBridge":false,"bridged":false,"bridgedAccessories":[],"reachable":true,"category":1,"services":[{"_events":{},"_eventsCount":2,"displayName":"","UUID":"0000003E-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":2,"displayName":"Identify","UUID":"00000014-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pw"]}},{"_events":{},"_eventsCount":1,"displayName":"Manufacturer","UUID":"00000020-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Manufacturer","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Model","UUID":"00000021-0000-1000-8000-0026BB765291","iid":null,"value":"Default-Model","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Upstairs","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Serial Number","UUID":"00000030-0000-1000-8000-0026BB765291","iid":null,"value":"Default-SerialNumber","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":1,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"0.0.0","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Accessory Flags","UUID":"000000A6-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"App Matching Identifier","UUID":"000000A4-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Configured Name","UUID":"000000E3-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Firmware Revision","UUID":"00000052-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Hardware Revision","UUID":"00000053-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Software Revision","UUID":"00000054-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Product Data","UUID":"00000220-0000-1000-8000-0026BB765291","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"data","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]},{"_events":{},"_eventsCount":2,"displayName":"Upstairs","UUID":"00000043-0000-1000-8000-0026BB765291","iid":null,"name":null,"characteristics":[{"_events":{},"_eventsCount":1,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"Upstairs","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":3,"displayName":"On","UUID":"00000025-0000-1000-8000-0026BB765291","iid":null,"value":false,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"bool","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":3,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}}],"optionalCharacteristics":[{"_events":{},"_eventsCount":0,"displayName":"Brightness","UUID":"00000008-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"int","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Hue","UUID":"00000013-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"arcdegrees","minValue":0,"maxValue":360,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Saturation","UUID":"0000002F-0000-1000-8000-0026BB765291","iid":null,"value":0,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"float","unit":"percentage","minValue":0,"maxValue":100,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Name","UUID":"00000023-0000-1000-8000-0026BB765291","iid":null,"value":"","status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"string","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}},{"_events":{},"_eventsCount":0,"displayName":"Color Temperature","UUID":"000000CE-0000-1000-8000-0026BB765291","iid":null,"value":140,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"uint32","unit":null,"minValue":140,"maxValue":500,"minStep":1,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Characteristic Value Transition Control","UUID":"0000021E-0000-1000-8000-00000143","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr","pw","ev"]}},{"_events":{},"_eventsCount":0,"displayName":"Supported Characteristic Value Transition Configuration","UUID":"0000021E-0000-1000-8000-00000144","iid":null,"value":null,"status":null,"eventOnlyCharacteristic":false,"subscriptions":0,"props":{"format":"tlv8","unit":null,"minValue":null,"maxValue":null,"minStep":null,"perms":["pr"]}}],"isHiddenService":false,"isPrimaryService":false,"linkedServices":[]}],"shouldPurgeUnusedIDs":true,"controllers":{},"_setupID":null,"controllerStorage":{"initialized":false,"fileCreated":false,"purgeUnidentifiedAccessoryData":true,"trackedControllers":[],"controllerData":{},"accessoryUUID":"a25ab181-230b-4e67-8e7d-c65d93906846"}},"displayName":"Upstairs","UUID":"a25ab181-230b-4e67-8e7d-c65d93906846","category":1})) }`

**Comment by scholtzan** [comment]
I just pushed an update (version 0.4.3) that has a fix which prevents the plugin from crashing when there are no active Spotify devices. This might also solve this issue.

**Comment by moshed** [comment]
I downloaded the new 0.4.4 and still no luck. id love to help out and try to get to the root of the issue if you'd like? if not no worries. dont want to be a bother!

**Comment by scholtzan** [comment]
Sure, feel free to investigate :)

**Comment by moshed** [comment]
ohh that's far beyond my abilities. I meant if you want to take time and try to troubleshoot with me and fix the issue. but again, if you're not up for that I dont want to be a bother. 

thanks for all your hard work!
